blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/Gorbiel/EnchantingConvergenceReenchanted/discussions
    about: Ask questions here instead of opening an issue